### PR TITLE
Better portability and small improvements

### PR DESCRIPTION
**Pull request by DominikRusso**

### CODE REVIEW

**Comment by DominikRusso** [comment]
`sed` isn't the only thing that doesn't work on BSD, needs further investigation.

**Comment by DominikRusso** [comment]
It looks like the problem was only a malformed contact file.

**Comment by DominikRusso** [comment]
No, there still is a problem and it's the cache file that isn't being written by the `sed` command correctly.

**Comment by DominikRusso** [comment]
BSD `sed` doesn't understand `\n`, it's not worth creating a workaround.

**Comment by Neo-Oli** [comment]
Thanks. I still think the changes are good so I added them in 568d0bb

**Pull request closed without merging**
